name: AppDaemon Dev
version: "0.1.0"
slug: appdaemon_dev
description: dev branch of AppDaemon
url: https://github.com/LogicAnalysis/haos-appdaemon-dev
webui: http://[HOST]:[PORT:5050]
arch:
- aarch64
- amd64
- armv7
init: false
homeassistant_api: true
uart: true
ports:
  5050/tcp: 5050
ports_description:
  5050/tcp: AppDaemon
map:
- addon_config:rw
- homeassistant_config:rw
- media:rw
- share:rw
- ssl
options:
  system_packages: []
  python_packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  system_packages:
  - str
  python_packages:
  - str
  init_commands:
  - str
image: ghcr.io/LogicAnalysis/haos-appdaemon-dev-{arch}
